### ISSUE TITLE
Manage merged cells

### ISSUE THREAD

**Issue by palevi67** [szyhf/go-excel#18]
I am trying to use go-excel to read an excel sheet that contains some merged cells in the same column (see attached image), that is, all the merged cells share the same value.

![image](https://github.com/user-attachments/assets/cba71bd0-1df1-4c0e-be7a-3f532915aefb)

When I import this sheet, only the value of the first cell appears, leaving the rest empty... shouldn't the value of the merged cells be imported into all the cells in the group?

**Comment by szyhf** [comment]
Sorry, currently can not support, excel itself data structure is a tree, and therefore can support more complex data model (for example, say you mentioned here merge cells), but the original intention of this library is used for rapid processing of relational databases shaped like excel table, in order to quickly read the data, itself is based on the use of the data structure is a much simpler structure of the scenario to achieve.
From the scenarios of the example you provided, the need for more complex and flexible processing tools, you can look at https://github.com/qax-os/excelize
---
Translated with www.DeepL.com/Translator (free version)
